export const NODE_TYPES = {
  reset:        { icon: '⏰', label: 'Reset',              model: '' },
  vf:           { icon: '🔍', label: 'ViralFinder',        model: '' },
  viralfinder:  { icon: '🔍', label: 'ViralFinder',        model: '' },
  video_analysis:{ icon: '🎥', label: 'VideoAnalysis',     model: '' },
  scriptwriter: { icon: '✍️', label: 'ScriptWriter',       model: '' },
  assetfinder:  { icon: '🎯', label: 'AssetFinder',        model: '' },
  videoeditor:  { icon: '🎬', label: 'VideoEditor',        model: '' },
  // Chemin alt (InfoMissed + images réelles)
  actufinder:   { icon: '📰', label: 'ActuFinder',         model: '' },
  actufinder_synthesize:{ icon: '🧬', label: 'Synthesize Article', model: 'qwen-opus' },
  actufinder_title_gate:{ icon: '🎯', label: 'Gate Personnage', model: 'qwen-opus' },
  scriptwriter_alt:{ icon: '📝', label: 'SW InfoMissed',   model: '' },
  alt_script_generator:{ icon: '📝', label: 'SW Gen (alt)', model: 'qwen3.6q2' },
  vo_coherence_review:{ icon: '🛡️', label: 'VO Coherence Review', model: 'qwen3.8-27b' },
  vo_shortener:{ icon: '✂️', label: 'VO Shortener',      model: 'qwen3.8-27b' },
  video_asset_fixer:{ icon: '🎬', label: 'Video Fix',      model: 'qwen3.8-27b' },
  script_fixer:{ icon: '🔧', label: 'Script Fixer',      model: 'qwen3.8-27b' },
  pydantic_script_validation_alt:{ icon: '✅', label: 'Pydantic SW (alt)', model: '' },
  validate_sw_alt:{ icon: '👤', label: 'Validation SW (alt)', model: 'Telegram' },
  assetfinder_alt:{ icon: '🎯', label: 'AssetFinder (Imgs)', model: '' },
  asset_planner_alt:{ icon: '📋', label: 'Planner Alt (2x I2V)', model: 'qwen-opus' },
  real_character_image:{ icon: '🖼️', label: 'Real Character Img', model: 'icrawler' },
  validate_character_refs:{ icon: '👤', label: 'Validation Perso', model: 'Telegram' },
  rewrite_i2v_prompt:{ icon: '✏️', label: 'Rewrite I2V Prompt', model: 'qwen3.6q2' },
  validate_i2v: { icon: '👤', label: 'Validation I2V',       model: 'Telegram' },
  alt_i2_v:     { icon: '🎥', label: 'Alt I2V',           model: 'LTX-Video 2.3' },
  alt_retry_gate:{ icon: '🔁', label: 'Alt Retry Gate',    model: '' },
  // ViralFinder subflow
  tikhub_search:{ icon: '🔍', label: 'TikHub',             model: 'qwen-opus' },
  tiktok_analyst:{icon: '📊', label: 'Analyst',            model: 'qwen-opus' },
  pydantic_validation: { icon: '✅', label: 'Pydantic',     model: '' },
  validate_vf:  { icon: '👤', label: 'Validation VF',      model: 'Telegram' },
  // VideoAnalysis subflow
  video_download:{ icon: '⬇️', label: 'VideoDownload',     model: '' },
  video_analysis_llm:{ icon: '🧠', label: 'AnalysisLLM',   model: 'gemma4-12b' },
  video_cleanup:{ icon: '🧹', label: 'Cleanup',            model: '' },
  // ScriptWriter subflow
  script_generator:{ icon: '📝', label: 'ScriptGen',       model: 'qwen3.6q2' },
  thinking_agent:{ icon: '🧠', label: 'Thinking Agent',    model: 'qwen3.8-27b' },
  brainstorm_thinking:{ icon: '💬', label: 'Brainstorm TG', model: 'qwen3.8-27b' },
  pydantic_script_validation: { icon: '✅', label: 'Pydantic SW', model: '' },
  validate_sw:  { icon: '👤', label: 'Validation SW',      model: 'Telegram' },
  // AssetFinder subflow
  asset_planner:{ icon: '📋', label: 'AssetPlanner',       model: 'qwen-opus' },
  cleanup_llama_proxy:{ icon: '🧹', label: 'CleanupLlama', model: '' },
  combined_cleanup:{ icon: '🧹', label: 'Cleanup All', model: '' },
  init_cleanup:{ icon: '🧹', label: 'Init Cleanup', model: '' },
  init_cleanup_alt:{ icon: '🧹', label: 'Init Cleanup (alt)', model: '' },
  sdcpp_video_gen:{ icon: '🎥', label: 'SDCpp Video',      model: 'LTX-Video' },
  comfyui_free_ltx:{ icon: '🧹', label: 'ComfyUI Free',    model: '' },
  comfyui_upscale:{ icon: '✨', label: 'Upscale RIFE',    model: '' },
  comfyui_free_audio:{ icon: '🧹', label: 'Free Audio',    model: '' },
  ffmpeg_upscaler:{ icon: '📐', label: 'Upscale FFmpeg',  model: 'lanczos' },
  sfx_generator:{ icon: '🎵', label: 'SFX (StableAudio)',  model: 'StableAudio3' },
  music_generator:{ icon: '🎶', label: 'Music (ACE-Step)', model: 'ACE-Step 1.5' },
  voice_generator:{ icon: '🗣️', label: 'Voice (FishSpeech)', model: 'Fish Speech S2' },
  montage_planner:{ icon: '📋', label: 'MontagePlanner',   model: 'qwen-opus' },
  montage_critic:{ icon: '🔍', label: 'MontageCritic',     model: 'qwen-opus' },
  validate_af:  { icon: '👤', label: 'Validation AF',      model: 'Telegram' },
  sdcpp_i2v_gen:{ icon: '🎥', label: 'SDCpp I2V',          model: 'LTX-Video 2.3' },
  comfyui_image_gen:{ icon: '🖼️', label: 'Gen Image',       model: 'Klein 4B' },
  i2v_cleanup:  { icon: '🧹', label: 'I2V Cleanup',        model: '' },
  i2v_video_cleanup:{ icon: '🧹', label: 'I2V Vid Cleanup', model: '' },
  comfyui_free_svg:{ icon: '🧹', label: 'Free SVG',         model: '' },
  comfyui_start_after_svg:{ icon: '🚀', label: 'ComfyUI Start', model: '' },
  // VideoEditor subflow
  videoeditor_planner:{ icon: '📋', label: 'VE Planner',   model: 'qwen-opus' },
  videoeditor_prepare:{ icon: '🔧', label: 'VE Prepare',   model: '' },
  videoeditor_clip:{ icon: '✂️', label: 'VE Clip',          model: '' },
  videoeditor_assemble:{ icon: '🎞️', label: 'VE Assemble',  model: '' },
  videoeditor_finalize:{ icon: '🏁', label: 'VE Finalize',  model: '' },
};
